### PR TITLE
remove unneeded heroku Procfile

### PR DESCRIPTION
**Pull request by zeke**
> To determine how to start your app, Heroku first looks for a Procfile. If no Procfile exists for a Node.js app, we will attempt to start a default web process via the start script in your package.json.

https://devcenter.heroku.com/articles/deploying-nodejs#specifying-a-start-script

### CODE REVIEW

**Comment by zeke** [comment]
bump

**Comment by AaronO** [comment]
@zeke Thanks, good catch.

**Comment by zeke** [comment]
👍

**Comment by zeke** [comment]
This PR was kind of a way to test the waters and see how actively maintained this project is. So thanks!

**Comment by AaronO** [comment]
@zeke `nuts` is actively used in production to power our [GitBook Desktop Editor](https://www.gitbook.com/editor) downloads. It's currently feature-complete for our needs and being maintained for bug-fixes.

Are you currently using or planning to use `nuts` in production ?

**Comment by zeke** [comment]
> Are you currently using or planning to use nuts in production ?

@AaronO  I'm evaluating nuts as a release server for Electron apps. Electron's [`autoUpdater` guide](https://github.com/electron/electron/blob/019883f2fa5bf3d56950988247cacb88b3c6f24f/docs/api/auto-updater.md) recommends it.

**Pull request merged**
